import React, { useState, useMemo, useEffect, useRef } from 'react';
import {
  Star,
  ShoppingCart,
  ShoppingBag,
  Check,
  ChevronLeft,
  ChevronRight,
  Images,
  Heart,
  MessageSquare,
  Send,
  User,
  CheckCircle2,
  Trash2,
  Share2,
  Maximize2,
  Play,
  ArrowLeft,
  Package,
  ShieldCheck,
  Truck,
  RotateCcw,
  Sparkles,
  Phone,
  HelpCircle,
  ExternalLink,
  AlertTriangle,
  Camera,
  UploadCloud,
  X,
  Filter,
  CheckCircle,
  ThumbsUp,
} from 'lucide-react';
import { Product, ProductReview } from '../types';
import { useStore } from '../context/StoreContext';
import { FormattedDescription } from './FormattedDescription';
import { ConfirmModal } from './ConfirmModal';
import { ProductCard } from './ProductCard';
import { parseColorOption } from '../utils/productVariants';
import { getYouTubeThumbnailUrl } from '../utils/youtube';
import { getResponsiveImageProps, getResponsiveImageUrl } from '../utils/responsiveImage';
import { formatWhatsAppLink } from '../utils/phone';
import { computeProductReviewStats, sortReviews, sanitizeReviewText } from '../utils/reviews';

interface ProductDetailViewProps {
  productId: string;
}

export const ProductDetailView: React.FC<ProductDetailViewProps> = ({ productId }) => {
  const {
    products,
    categories,
    settings,
    addToCart,
    quickBuy,
    wishlist,
    toggleWishlist,
    reviews,
    addProductReview,
    deleteProductReview,
    copyProductLink,
    getProductUrl,
    getCategoryUrl,
    setSelectedCategory,
    navigateToCategory,
    openProductVideo,
    currentUser,
    isAdminLoggedIn,
    hasPermission,
    trackEvent,
    homepageCategoryProducts,
    singleProduct,
    isProductLoading,
    productNotFound,
    loadProductById,
    currentView,
    selectedProductId,
    setCurrentView,
    setSelectedProductId,
    showNotification,
  } = useStore();

  const [quantity, setQuantity] = useState(1);
  const [selectedSize, setSelectedSize] = useState<string | undefined>(undefined);
  const [selectedColor, setSelectedColor] = useState<string | undefined>(undefined);
  const [validationError, setValidationError] = useState<string | null>(null);
  const [addedNotice, setAddedNotice] = useState(false);
  const [selectedImageIdx, setSelectedImageIdx] = useState(0);
  const [activeTab, setActiveTab] = useState<'overview' | 'reviews'>('overview');
  const [isFullscreenOpen, setIsFullscreenOpen] = useState(false);

  // Professional Review System States
  const [reviewRating, setReviewRating] = useState(5);
  const [hoverRating, setHoverRating] = useState<number | null>(null);
  const [reviewAuthor, setReviewAuthor] = useState('');
  const [reviewComment, setReviewComment] = useState('');
  const [reviewImages, setReviewImages] = useState<string[]>([]);
  const [reviewImageUrlInput, setReviewImageUrlInput] = useState('');
  const [reviewOrderNumber, setReviewOrderNumber] = useState('');
  const [reviewPhone, setReviewPhone] = useState('');
  const [isSubmittingReview, setIsSubmittingReview] = useState(false);
  const [reviewError, setReviewError] = useState<string | null>(null);
  const [reviewSuccessMsg, setReviewSuccessMsg] = useState('');
  const [showReviewForm, setShowReviewForm] = useState(false);
  const [reviewSortBy, setReviewSortBy] = useState<'newest' | 'oldest' | 'highest' | 'lowest' | 'photos'>('newest');
  const [reviewStarFilter, setReviewStarFilter] = useState<number | 'all'>('all');
  const [previewReviewImage, setPreviewReviewImage] = useState<{ url: string; author: string; rating: number } | null>(null);

  const [confirmDialog, setConfirmDialog] = useState<{
    isOpen: boolean;
    title: string;
    message: string;
    confirmText?: string;
    cancelText?: string;
    variant?: 'danger' | 'warning' | 'primary';
    onConfirm: () => void;
  }>({
    isOpen: false,
    title: '',
    message: '',
    onConfirm: () => {},
  });

  // Fetch product directly from server on mount or when productId prop changes
  useEffect(() => {
    if (productId) {
      loadProductById(productId);
    }
    // Scroll window smoothly to top when viewing a new product
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, [productId, loadProductById]);

  // Use the fetched product or the matching one from products (matches by slug, id, or normalized title)
  const product = singleProduct || products.find((p) => p.slug === productId || p.id === productId || p.title.toLowerCase().replace(/[^a-z0-9]+/g, '-') === productId) || null;

  // Dynamic URL Synchronization:
  // As soon as a single product is viewed or loaded, automatically update the browser's
  // address bar URL to reflect the canonical SEO slug (e.g. /product/excel-ep-06-20000mah-22-5w-power-bank),
  // matching the URL generated by the share button without reloading the page.
  useEffect(() => {
    if (!product || typeof window === 'undefined') return;

    const targetUrl = getProductUrl(product);
    const currentPath = window.location.pathname;

    // Dynamically update the address bar without reloading the page
    if (currentPath !== targetUrl) {
      window.history.replaceState(
        { ...window.history.state, productId: product.id, slug: product.slug },
        document.title,
        targetUrl
      );
    }

    const activeIdentifier = product.slug || product.id;
    if (selectedProductId !== activeIdentifier) {
      setSelectedProductId(activeIdentifier);
    }
    if (currentView !== 'product') {
      setCurrentView('product');
    }
  }, [product, getProductUrl, selectedProductId, setSelectedProductId, currentView, setCurrentView]);

  const category = categories.find((c) => c.id === product?.categoryId);

  // Extract all images (primary + any gallery photos)
  const imageList = useMemo(() => {
    if (!product) return [];
    const set = new Set<string>();
    if (product.imageUrl) set.add(product.imageUrl.trim());
    if (product.images && Array.isArray(product.images)) {
      product.images.forEach((img) => {
        if (img && img.trim()) set.add(img.trim());
      });
    }
    return Array.from(set);
  }, [product]);

  // Related products from same category
  const relatedProducts = useMemo(() => {
    if (!product) return [];
    const pool = (homepageCategoryProducts[product.categoryId] && homepageCategoryProducts[product.categoryId].length > 0)
      ? homepageCategoryProducts[product.categoryId]
      : products.filter((p) => p.categoryId === product.categoryId);
    return pool.filter((p) => p.id !== product.id).slice(0, 4);
  }, [product, products, homepageCategoryProducts]);

  // Track ProductView / ViewContent event
  useEffect(() => {
    if (product) {
      trackEvent('ProductView', {
        content_name: product.title,
        content_ids: [product.id],
        content_type: 'product',
        value: product.price,
        currency: 'BDT',
      });
    }
  }, [product?.id]);

  // Initialize variant defaults when product loads
  useEffect(() => {
    setSelectedImageIdx(0);
    setQuantity(1);
    setActiveTab('overview');
    setReviewSuccessMsg('');
    setIsFullscreenOpen(false);

    if (product?.sizes && product.sizes.length === 1) {
      setSelectedSize(product.sizes[0]);
    } else {
      setSelectedSize(undefined);
    }
    if (product?.colors && product.colors.length === 1) {
      setSelectedColor(product.colors[0]);
    } else {
      setSelectedColor(undefined);
    }
    setValidationError(null);
    if (currentUser?.name) {
      setReviewAuthor(currentUser.name);
    } else {
      setReviewAuthor('');
    }
  }, [product?.id, currentUser]);

  const canDeleteReview = Boolean(
    isAdminLoggedIn ||
    currentUser?.role === 'super_admin' ||
    currentUser?.role === 'admin' ||
    (currentUser?.role === 'sub_admin' && hasPermission('canManageProducts'))
  );

  const handleBackToHome = () => {
    setCurrentView('store');
    setSelectedProductId(null);
    setSelectedCategory(null);
    if (window.location.pathname !== '/' || window.location.search) {
      window.history.pushState({}, '', '/');
    }
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  // 1. Loading Skeleton State
  if (isProductLoading && !product) {
    return (
      <div className="py-6 sm:py-10 max-w-7xl mx-auto">
        {/* Breadcrumb Skeleton */}
        <div className="flex items-center gap-2 mb-6">
          <div className="h-4 w-16 bg-slate-200 rounded-md animate-pulse" />
          <span className="text-slate-300">/</span>
          <div className="h-4 w-28 bg-slate-200 rounded-md animate-pulse" />
          <span className="text-slate-300">/</span>
          <div className="h-4 w-40 bg-slate-200 rounded-md animate-pulse" />
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 bg-white rounded-3xl p-4 sm:p-8 border border-slate-200/80 shadow-xs">
          {/* Left Column: Image Skeleton */}
          <div className="lg:col-span-6 space-y-4">
            <div className="aspect-square w-full rounded-2xl bg-slate-200 animate-pulse" />
            <div className="flex gap-2">
              <div className="w-16 h-16 rounded-xl bg-slate-200 animate-pulse" />
              <div className="w-16 h-16 rounded-xl bg-slate-200 animate-pulse" />
              <div className="w-16 h-16 rounded-xl bg-slate-200 animate-pulse" />
            </div>
          </div>

          {/* Right Column: Details Skeleton */}
          <div className="lg:col-span-6 space-y-5">
            <div className="h-6 w-24 bg-slate-200 rounded-full animate-pulse" />
            <div className="h-8 w-3/4 bg-slate-200 rounded-xl animate-pulse" />
            <div className="h-5 w-32 bg-slate-200 rounded-md animate-pulse" />
            <div className="h-10 w-44 bg-slate-200 rounded-xl animate-pulse" />
            <div className="h-24 w-full bg-slate-100 rounded-xl animate-pulse" />
            <div className="grid grid-cols-2 gap-3 pt-4">
              <div className="h-12 rounded-xl bg-slate-200 animate-pulse" />
              <div className="h-12 rounded-xl bg-slate-200 animate-pulse" />
            </div>
          </div>
        </div>
      </div>
    );
  }

  // 2. 404 Product Not Found State
  if (productNotFound || (!product && !isProductLoading)) {
    const supportWhatsAppNumber = settings.footer?.supportWhatsApp || settings.phone || '';
    const whatsappHref = formatWhatsAppLink(
      supportWhatsAppNumber,
      `Hello ${settings.siteName || 'Rongdhonu Trade'}! I was looking for product "${productId}", but it was not found.`
    );

    return (
      <div className="py-12 sm:py-16 max-w-4xl mx-auto px-4 text-center">
        <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-8 sm:p-12 space-y-6">
          <div className="w-20 h-20 rounded-3xl bg-rose-50 text-rose-500 flex items-center justify-center mx-auto border border-rose-100 shadow-xs">
            <Package className="w-10 h-10" />
          </div>

          <div className="space-y-2 max-w-lg mx-auto">
            <span className="inline-block px-3 py-1 rounded-full bg-rose-100/80 text-rose-700 text-xs font-bold uppercase tracking-wider">
              404 — Not Found
            </span>
            <h1 className="font-display font-extrabold text-2xl sm:text-3xl text-slate-900">
              Product Not Found
            </h1>
            <p className="text-sm text-slate-500 leading-relaxed">
              The product you are looking for ({productId ? `"${productId}"` : 'this link'}) was not found or has been removed from our catalog.
            </p>
          </div>

          <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
            <button
              type="button"
              onClick={handleBackToHome}
              className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-slate-900 hover:bg-black text-white text-xs sm:text-sm font-bold shadow-md hover:shadow-lg active:scale-95 transition-all cursor-pointer"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Back to All Products</span>
            </button>

            {supportWhatsAppNumber && (
              <a
                href={whatsappHref}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs sm:text-sm font-bold shadow-md hover:shadow-lg active:scale-95 transition-all cursor-pointer"
              >
                <Phone className="w-4 h-4" />
                <span>Contact WhatsApp Support</span>
              </a>
            )}
          </div>
        </div>

        {/* Suggest other available products so user is not stuck */}
        {products.length > 0 && (
          <div className="mt-12 text-left">
            <h2 className="font-display font-bold text-xl text-slate-800 mb-6">
              Popular Items You Might Like
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
              {products.slice(0, 4).map((p) => (
                <ProductCard key={p.id} product={p} />
              ))}
            </div>
          </div>
        )}
      </div>
    );
  }

  // 3. Normal Product Display
  const activeImage = imageList[selectedImageIdx] || product.imageUrl;
  const isSavedInWishlist = wishlist.includes(product.id);
  // Public Approved Product Reviews & Live Dynamic Stats
  const productReviews = useMemo(() => {
    if (!product) return [];
    return (reviews || []).filter(
      (r) =>
        (r.productId === product.id || r.productId === product.slug) &&
        (!r.status || r.status === 'approved')
    );
  }, [reviews, product]);

  const reviewStats = useMemo(() => {
    return computeProductReviewStats(
      productReviews,
      product?.rating ?? 5.0,
      product?.reviewsCount ?? 0
    );
  }, [productReviews, product]);

  const filteredAndSortedReviews = useMemo(() => {
    let list = [...productReviews];
    if (reviewStarFilter !== 'all') {
      list = list.filter((r) => Math.round(Number(r.rating) || 5) === reviewStarFilter);
    }
    return sortReviews(list, reviewSortBy);
  }, [productReviews, reviewStarFilter, reviewSortBy]);

  const reviewsWithPhotosCount = useMemo(() => {
    return productReviews.filter((r) => r.images && r.images.length > 0).length;
  }, [productReviews]);

  const handlePhotoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files || files.length === 0) return;
    if (reviewImages.length + files.length > 5) {
      showNotification('warning', 'Photo Limit', 'You can upload a maximum of 5 photos.');
      return;
    }

    Array.from(files).forEach((file: File) => {
      if (!file.type.startsWith('image/')) return;
      if (file.type === 'image/svg+xml' || file.name.toLowerCase().endsWith('.svg')) {
        showNotification('error', 'Unsupported Format', 'Vector graphics (SVG) are strictly prohibited for security reasons.');
        return;
      }
      if (file.size > 2 * 1024 * 1024) {
        showNotification('error', 'File Too Large', 'Each review photo must be under 2MB.');
        return;
      }
      const reader = new FileReader();
      reader.onload = (ev) => {
        const result = ev.target?.result as string;
        if (result) {
          setReviewImages((prev) => (prev.length < 5 ? [...prev, result] : prev));
        }
      };
      reader.readAsDataURL(file);
    });
    e.target.value = '';
  };

  const handleAddImageUrl = () => {
    if (!reviewImageUrlInput.trim()) return;
    if (reviewImages.length >= 5) {
      showNotification('warning', 'Photo Limit', 'Maximum 5 photos allowed.');
      return;
    }
    setReviewImages((prev) => [...prev, reviewImageUrlInput.trim()]);
    setReviewImageUrlInput('');
  };

  const handleRemovePhoto = (idx: number) => {
    setReviewImages((prev) => prev.filter((_, i) => i !== idx));
  };

  const totalReviewsCount = reviewStats.totalReviews;

  const discountPercent =
    product.originalPrice && product.originalPrice > product.price
      ? Math.round(((product.originalPrice - product.price) / product.originalPrice) * 100)
      : 0;

  const hasVideo = Boolean(product.videoUrl && product.videoUrl.trim());
  const isOutOfStock = product.stock <= 0;

  const validateVariantSelection = (): { valid: boolean; color?: string; size?: string } => {
    const hasMultipleColors = Boolean(product?.colors && product.colors.length > 1);
    const hasMultipleSizes = Boolean(product?.sizes && product.sizes.length > 1);

    const resolvedColor =
      selectedColor || (product?.colors && product.colors.length === 1 ? product.colors[0] : undefined);
    const resolvedSize =
      selectedSize || (product?.sizes && product.sizes.length === 1 ? product.sizes[0] : undefined);

    const isColorMissing = hasMultipleColors && !resolvedColor;
    const isSizeMissing = hasMultipleSizes && !resolvedSize;

    if (isColorMissing && isSizeMissing) {
      const msg = 'Please select a color and size.';
      setValidationError(msg);
      showNotification('warning', 'Selection Required', msg);
      return { valid: false };
    }
    if (isColorMissing) {
      const msg = 'Please select a color.';
      setValidationError(msg);
      showNotification('warning', 'Color Required', msg);
      return { valid: false };
    }
    if (isSizeMissing) {
      const msg = 'Please select a size.';
      setValidationError(msg);
      showNotification('warning', 'Size Required', msg);
      return { valid: false };
    }

    setValidationError(null);
    return { valid: true, color: resolvedColor, size: resolvedSize };
  };

  const handleAddToCart = () => {
    const { valid, color, size } = validateVariantSelection();
    if (!valid) return;

    addToCart(product, quantity, size, color);
    setAddedNotice(true);
    setTimeout(() => {
      setAddedNotice(false);
    }, 1200);
  };

  const handleQuickBuy = () => {
    const { valid, color, size } = validateVariantSelection();
    if (!valid) return;

    quickBuy(product, size, color);
  };

  const handleReviewSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!product) return;
    setReviewError(null);

    const cleanAuthor = sanitizeReviewText(reviewAuthor.trim() || currentUser?.name || 'Customer');
    const cleanComment = sanitizeReviewText(reviewComment.trim());

    if (!cleanAuthor || cleanAuthor.length < 2) {
      setReviewError('Please enter a valid name (at least 2 characters).');
      return;
    }
    if (!cleanComment || cleanComment.length < 3) {
      setReviewError('Please write a review comment (at least 3 characters).');
      return;
    }
    if (cleanComment.length > 1000) {
      setReviewError('Review comment cannot exceed 1000 characters.');
      return;
    }

    setIsSubmittingReview(true);
    try {
      const res = await addProductReview({
        productId: product.id,
        authorName: cleanAuthor,
        rating: reviewRating,
        comment: cleanComment,
        images: reviewImages,
        orderNumber: reviewOrderNumber.trim() || undefined,
        phone: reviewPhone.trim() || undefined,
      });

      if (res.success) {
        setReviewComment('');
        setReviewImages([]);
        setReviewOrderNumber('');
        setReviewPhone('');
        setShowReviewForm(false);
        setReviewSuccessMsg(res.message || 'Thank you! Your review has been submitted.');
        setTimeout(() => setReviewSuccessMsg(''), 6000);
      } else {
        setReviewError(res.message || 'Could not submit review. Please try again.');
      }
    } catch (err: any) {
      setReviewError(err?.message || 'Failed to submit review.');
    } finally {
      setIsSubmittingReview(false);
    }
  };

  return (
    <div className="py-3 sm:py-6 space-y-8">
      {/* Breadcrumb Navigation */}
      <nav aria-label="Breadcrumb" className="flex items-center gap-1.5 sm:gap-2 text-xs text-slate-500 flex-wrap">
        <a
          href="/"
          onClick={(e) => {
            if (e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;
            e.preventDefault();
            handleBackToHome();
          }}
          className="underline decoration-slate-300 underline-offset-4 hover:decoration-rose-500 hover:text-rose-600 focus:outline-none focus:ring-2 focus:ring-rose-500/40 focus:ring-offset-1 rounded-xs transition-colors font-medium"
        >
          Home
        </a>
        <span className="text-slate-300">/</span>
        {category && (
          <>
            <a
              href={getCategoryUrl(category.slug || category.id)}
              onClick={(e) => {
                if (e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;
                e.preventDefault();
                navigateToCategory(category.id);
              }}
              className="underline decoration-slate-300 underline-offset-4 hover:decoration-rose-500 hover:text-rose-600 focus:outline-none focus:ring-2 focus:ring-rose-500/40 focus:ring-offset-1 rounded-xs transition-colors font-medium"
            >
              {category.name}
            </a>
            <span className="text-slate-300">/</span>
          </>
        )}
        <span className="text-slate-800 font-bold truncate max-w-[240px] sm:max-w-md" aria-current="page">
          {product.title}
        </span>
      </nav>

      {/* Main Product Container */}
      <div className="bg-white rounded-3xl border border-slate-200 shadow-xs overflow-hidden">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 lg:gap-10 p-4 sm:p-6 lg:p-8">
          {/* Left Column: Image Gallery */}
          <div className="lg:col-span-6 flex flex-col gap-3">
            {/* Primary Large Image */}
            <div className="relative aspect-square w-full rounded-2xl bg-slate-100 overflow-hidden border border-slate-200/90 group/gallery">
              <img
                {...getResponsiveImageProps(activeImage, 'detail', { priority: true })}
                alt={`${product.title} - view ${selectedImageIdx + 1}`}
                onClick={() => setIsFullscreenOpen(true)}
                className="w-full h-full object-cover object-center cursor-zoom-in transition-all duration-300 group-hover/gallery:scale-105"
              />

              {/* Badges Overlay */}
              <div className="absolute top-3.5 left-3.5 flex flex-col gap-1.5 z-10">
                {discountPercent > 0 && (
                  <span className="px-3 py-1 rounded-full text-xs font-extrabold tracking-wider text-white bg-rose-600 shadow-md">
                    {discountPercent}% OFF
                  </span>
                )}
                {product.stock <= 5 && product.stock > 0 && (
                  <span className="px-3 py-1 rounded-full text-xs font-bold bg-amber-500 text-white shadow-md">
                    Only {product.stock} Left!
                  </span>
                )}
                {isOutOfStock && (
                  <span className="px-3 py-1 rounded-full text-xs font-bold bg-slate-900 text-white shadow-md">
                    Sold Out
                  </span>
                )}
              </div>

              {/* Floating Wishlist Button */}
              <div className="absolute top-3.5 right-3.5 z-20">
                <button
                  type="button"
                  onClick={() => toggleWishlist(product.id)}
                  className={`w-9 h-9 rounded-full flex items-center justify-center transition-all shadow-md ${
                    isSavedInWishlist
                      ? 'bg-rose-50 text-rose-600 ring-2 ring-rose-500 scale-105'
                      : 'bg-white/90 hover:bg-white text-slate-600 hover:text-rose-600'
                  }`}
                  title={isSavedInWishlist ? 'Remove from Wishlist' : 'Add to Wishlist'}
                  aria-label="Toggle Wishlist"
                >
                  <Heart className={`w-4 h-4 ${isSavedInWishlist ? 'fill-rose-500 text-rose-500' : ''}`} />
                </button>
              </div>

              {/* Bottom Actions: Fullscreen Lightbox & Video Button */}
              <div className="absolute bottom-3.5 left-3.5 z-20 flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => setIsFullscreenOpen(true)}
                  className="px-3 py-1.5 rounded-xl bg-white/95 hover:bg-white text-slate-800 text-xs font-bold flex items-center gap-1.5 shadow-md backdrop-blur-xs transition-all hover:scale-105 active:scale-95 border border-slate-200/80 cursor-pointer"
                  title="Expand photo full-screen"
                >
                  <Maximize2 className="w-3.5 h-3.5 text-slate-700" />
                  <span className="hidden sm:inline">Zoom Photo</span>
                </button>

                {hasVideo && (
                  <button
                    type="button"
                    onClick={() => openProductVideo(product, 'popup')}
                    className="px-3 py-1.5 rounded-xl bg-rose-600 hover:bg-rose-700 text-white text-xs font-bold flex items-center gap-1.5 shadow-md shadow-rose-600/25 transition-all hover:scale-105 active:scale-95 cursor-pointer"
                    title="Watch video demo"
                  >
                    <Play className="w-3.5 h-3.5 fill-white" />
                    <span>Watch Video</span>
                  </button>
                )}
              </div>

              {/* Prev / Next Arrows */}
              {imageList.length > 1 && (
                <>
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      setSelectedImageIdx((prev) => (prev > 0 ? prev - 1 : imageList.length - 1));
                    }}
                    className="absolute left-3 top-1/2 -translate-y-1/2 w-9 h-9 rounded-full bg-white/90 hover:bg-white text-slate-800 flex items-center justify-center shadow-md transition-transform hover:scale-110 z-10 cursor-pointer"
                    title="Previous photo"
                  >
                    <ChevronLeft className="w-5 h-5" />
                  </button>
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      setSelectedImageIdx((prev) => (prev < imageList.length - 1 ? prev + 1 : 0));
                    }}
                    className="absolute right-3 top-1/2 -translate-y-1/2 w-9 h-9 rounded-full bg-white/90 hover:bg-white text-slate-800 flex items-center justify-center shadow-md transition-transform hover:scale-110 z-10 cursor-pointer"
                    title="Next photo"
                  >
                    <ChevronRight className="w-5 h-5" />
                  </button>

                  <span className="absolute bottom-3.5 right-3.5 px-2.5 py-1 rounded-full bg-slate-900/80 backdrop-blur-xs text-white text-xs font-bold flex items-center gap-1.5 shadow-xs z-10 pointer-events-none">
                    <Images className="w-3.5 h-3.5 text-rose-400" />
                    {selectedImageIdx + 1} / {imageList.length}
                  </span>
                </>
              )}
            </div>

            {/* Thumbnail Strip */}
            {(imageList.length > 1 || hasVideo) && (
              <div className="flex items-center gap-2 overflow-x-auto p-1 py-2 [-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
                {imageList.map((img, idx) => (
                  <button
                    key={idx}
                    type="button"
                    onClick={() => setSelectedImageIdx(idx)}
                    className={`relative w-16 h-16 rounded-xl overflow-hidden shrink-0 border-2 transition-all cursor-pointer ${
                      selectedImageIdx === idx
                        ? 'border-rose-600 ring-2 ring-rose-200 scale-105'
                        : 'border-slate-200 opacity-60 hover:opacity-100 hover:border-slate-400'
                    }`}
                    title={`View photo ${idx + 1}`}
                  >
                    <img
                      src={getResponsiveImageUrl(img, 240)}
                      width={64}
                      height={64}
                      alt={`Thumbnail ${idx + 1}`}
                      loading="lazy"
                      decoding="async"
                      className="w-full h-full object-cover"
                    />
                  </button>
                ))}

                {hasVideo && product.videoUrl && (
                  <button
                    type="button"
                    onClick={() => openProductVideo(product, 'popup')}
                    className="relative w-16 h-16 rounded-xl overflow-hidden shrink-0 border-2 border-rose-500 ring-1 ring-rose-200 hover:scale-105 transition-all cursor-pointer bg-slate-900 group"
                    title="Watch Product Video Demo"
                  >
                    {getYouTubeThumbnailUrl(product.videoUrl, 'mq') ? (
                      <img
                        src={getYouTubeThumbnailUrl(product.videoUrl, 'mq')!}
                        alt={`${product.title} video`}
                        loading="lazy"
                        decoding="async"
                        className="w-full h-full object-cover opacity-70 group-hover:opacity-95"
                      />
                    ) : (
                      <img
                        src={getResponsiveImageUrl(product.imageUrl, 240)}
                        width={64}
                        height={64}
                        alt="video thumbnail"
                        loading="lazy"
                        decoding="async"
                        className="w-full h-full object-cover opacity-60"
                      />
                    )}
                    <div className="absolute inset-0 bg-black/40 flex items-center justify-center">
                      <div className="w-6 h-6 rounded-full bg-rose-600 text-white flex items-center justify-center shadow-sm group-hover:scale-110 transition-transform">
                        <Play className="w-3 h-3 fill-white ml-0.5" />
                      </div>
                    </div>
                  </button>
                )}
              </div>
            )}
          </div>

          {/* Right Column: Details & Actions */}
          <div className="lg:col-span-6 flex flex-col justify-between space-y-6">
            <div className="space-y-4">
              {/* Category & Status */}
              <div className="flex items-center justify-between gap-2">
                {category && (
                  <a
                    href={getCategoryUrl(category.slug || category.id)}
                    onClick={(e) => {
                      if (e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;
                      e.preventDefault();
                      navigateToCategory(category.id);
                    }}
                    className="inline-block text-xs font-bold text-rose-600 uppercase tracking-wider bg-rose-50 hover:bg-rose-100 px-3 py-1 rounded-lg transition-colors cursor-pointer"
                  >
                    {category.name}
                  </a>
                )}

                <span
                  className={`text-xs font-bold px-3 py-1 rounded-full ${
                    product.stock > 0
                      ? 'bg-emerald-50 text-emerald-700 border border-emerald-200'
                      : 'bg-rose-50 text-rose-700 border border-rose-200'
                  }`}
                >
                  {product.stock > 0 ? 'In Stock' : 'Out of Stock'}
                </span>
              </div>

              {/* Title & Share Action */}
              <div className="flex items-start justify-between gap-3">
                <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold font-display text-slate-900 leading-tight">
                  {product.title}
                </h1>
                <button
                  type="button"
                  onClick={() => copyProductLink(product.id)}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full border border-slate-200 bg-white hover:bg-rose-50 hover:border-rose-200 text-slate-700 hover:text-rose-600 text-xs font-semibold shadow-xs hover:shadow transition-all shrink-0 cursor-pointer group mt-0.5"
                  title="Share Product"
                  aria-label="Share Product"
                >
                  <Share2 className="w-3.5 h-3.5 text-slate-500 group-hover:text-rose-600 transition-colors" />
                  <span>Share</span>
                </button>
              </div>

              {/* Star Rating & Reviews Summary */}
              <div className="flex items-center gap-3">
                <div className="flex items-center text-amber-400">
                  {[1, 2, 3, 4, 5].map((starIdx) => (
                    <Star
                      key={starIdx}
                      className={`w-4 h-4 ${
                        starIdx <= Math.round(reviewStats.averageRating)
                          ? 'fill-amber-400 text-amber-400'
                          : 'text-slate-300'
                      }`}
                    />
                  ))}
                </div>
                <span className="text-sm font-bold text-slate-800 font-mono">
                  {reviewStats.averageRating.toFixed(1)} / 5.0
                </span>
                <button
                  type="button"
                  onClick={() => {
                    setActiveTab('reviews');
                    const el = document.getElementById('product-tabs-section');
                    if (el) el.scrollIntoView({ behavior: 'smooth' });
                  }}
                  className="text-xs text-rose-600 hover:text-rose-700 font-semibold underline cursor-pointer"
                >
                  ({reviewStats.totalReviews} {reviewStats.totalReviews === 1 ? 'verified review' : 'verified reviews'})
                </button>
              </div>

              {/* Pricing Section */}
              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/90 flex items-baseline justify-between gap-4">
                <div className="space-y-1">
                  <span className="text-xs text-slate-500 font-medium">Special Price</span>
                  <div className="flex items-baseline gap-2.5">
                    <span className="text-2xl sm:text-3xl font-extrabold font-display text-slate-900">
                      ৳ {product.price.toLocaleString()}
                    </span>
                    <span className="text-xs font-bold text-slate-500">BDT</span>
                    {product.originalPrice && product.originalPrice > product.price && (
                      <span className="text-sm sm:text-base text-slate-400 line-through">
                        ৳ {product.originalPrice.toLocaleString()}
                      </span>
                    )}
                  </div>
                </div>

                {discountPercent > 0 && (
                  <span className="px-3 py-1.5 rounded-xl bg-rose-600 text-white font-extrabold text-xs shadow-xs">
                    Save {discountPercent}%
                  </span>
                )}
              </div>

              {/* Color Variants */}
              {product.colors && product.colors.length > 0 && (
                <div
                  className={`rounded-xl transition-all ${
                    validationError && product.colors.length > 1 && !selectedColor
                      ? 'p-2.5 ring-2 ring-rose-400 bg-rose-50/50'
                      : 'space-y-2'
                  }`}
                >
                  <div className="flex items-center justify-between text-xs">
                    <span className="font-bold text-slate-700">Available Colors:</span>
                    <span className="font-semibold text-rose-600">
                      {selectedColor ? parseColorOption(selectedColor).name : 'Choose a color'}
                    </span>
                  </div>
                  <div className="flex items-center gap-2 flex-wrap">
                    {product.colors.map((color, idx) => {
                      const parsed = parseColorOption(color);
                      const isSelected = selectedColor === color;
                      return (
                        <button
                          key={idx}
                          type="button"
                          onClick={() => {
                            setSelectedColor(color);
                            setValidationError(null);
                          }}
                          className={`group flex items-center gap-2 px-3 py-1.5 rounded-xl border text-xs font-bold transition-all cursor-pointer ${
                            isSelected
                              ? 'border-slate-900 bg-slate-900 text-white shadow-xs'
                              : 'border-slate-200 bg-white hover:border-slate-300 text-slate-700'
                          }`}
                          title={parsed.name}
                        >
                          <span
                            className={`w-3.5 h-3.5 rounded-full border ${
                              parsed.isLight ? 'border-slate-300' : 'border-white/50'
                            }`}
                            style={{ backgroundColor: parsed.hex }}
                          />
                          <span>{parsed.name}</span>
                        </button>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* Size Variants */}
              {product.sizes && product.sizes.length > 0 && (
                <div
                  className={`rounded-xl transition-all ${
                    validationError && product.sizes.length > 1 && !selectedSize
                      ? 'p-2.5 ring-2 ring-rose-400 bg-rose-50/50'
                      : 'space-y-2'
                  }`}
                >
                  <div className="flex items-center justify-between text-xs">
                    <span className="font-bold text-slate-700">Size / Option:</span>
                    <span className="font-semibold text-rose-600">{selectedSize || 'Choose a size'}</span>
                  </div>
                  <div className="flex items-center gap-2 flex-wrap">
                    {product.sizes.map((size, idx) => {
                      const isSelected = selectedSize === size;
                      return (
                        <button
                          key={idx}
                          type="button"
                          onClick={() => {
                            setSelectedSize(size);
                            setValidationError(null);
                          }}
                          className={`px-3.5 py-1.5 rounded-xl border text-xs font-bold transition-all cursor-pointer ${
                            isSelected
                              ? 'border-rose-600 bg-rose-50 text-rose-700 ring-2 ring-rose-200'
                              : 'border-slate-200 bg-white hover:border-slate-300 text-slate-700'
                          }`}
                        >
                          {size}
                        </button>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* Quantity Selector */}
              <div className="flex items-center justify-between py-2 border-y border-slate-100">
                <span className="text-xs font-bold text-slate-700">Quantity:</span>
                <div className="flex items-center border border-slate-300 rounded-xl overflow-hidden bg-white shadow-2xs">
                  <button
                    type="button"
                    onClick={() => setQuantity((q) => Math.max(1, q - 1))}
                    disabled={quantity <= 1 || isOutOfStock}
                    className="w-8 h-8 flex items-center justify-center text-slate-600 hover:bg-slate-100 disabled:opacity-30 disabled:pointer-events-none transition-colors"
                  >
                    -
                  </button>
                  <span className="w-10 text-center text-xs font-bold text-slate-800">
                    {quantity}
                  </span>
                  <button
                    type="button"
                    onClick={() => setQuantity((q) => Math.min(product.stock || 99, q + 1))}
                    disabled={quantity >= product.stock || isOutOfStock}
                    className="w-8 h-8 flex items-center justify-center text-slate-600 hover:bg-slate-100 disabled:opacity-30 disabled:pointer-events-none transition-colors"
                  >
                    +
                  </button>
                </div>
              </div>

              {/* Validation Warning Alert */}
              {validationError && (
                <div
                  id="product-detail-variant-validation-alert"
                  className="p-3 rounded-xl bg-amber-50 border border-amber-300 text-amber-900 text-xs font-bold flex items-center gap-2 animate-in fade-in duration-200"
                  role="alert"
                >
                  <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0" />
                  <span>{validationError}</span>
                </div>
              )}

              {/* Call To Action Buttons: Add to Cart & Buy Now */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2">
                <button
                  type="button"
                  id="product-detail-add-to-cart-btn"
                  onClick={handleAddToCart}
                  disabled={isOutOfStock}
                  className="py-3 px-4 rounded-xl border-2 border-rose-600 text-rose-600 hover:bg-rose-50 active:bg-rose-100 font-bold text-xs sm:text-sm flex items-center justify-center gap-2 shadow-xs active:scale-95 transition-all disabled:opacity-40 disabled:pointer-events-none cursor-pointer"
                >
                  {addedNotice ? (
                    <>
                      <Check className="w-4 h-4 text-emerald-600" />
                      <span className="text-emerald-700">Added to Cart!</span>
                    </>
                  ) : (
                    <>
                      <ShoppingCart className="w-4 h-4" />
                      <span>Add to Cart</span>
                    </>
                  )}
                </button>

                <button
                  type="button"
                  id="product-detail-buy-now-btn"
                  onClick={handleQuickBuy}
                  disabled={isOutOfStock}
                  className="py-3 px-4 rounded-xl bg-slate-900 hover:bg-black active:bg-slate-950 text-white font-bold text-xs sm:text-sm flex items-center justify-center gap-2 shadow-md hover:shadow-lg active:scale-95 transition-all disabled:opacity-40 disabled:pointer-events-none cursor-pointer"
                >
                  <ShoppingBag className="w-4 h-4 text-amber-400" />
                  <span>Buy Now (অর্ডার করুন)</span>
                </button>
              </div>

              {/* Value Propositions / Trust Signals */}
              <div className="grid grid-cols-3 gap-2 pt-3 border-t border-slate-100 text-center">
                <div className="p-2.5 rounded-xl bg-slate-50 border border-slate-100 space-y-1">
                  <Truck className="w-4 h-4 text-rose-500 mx-auto" />
                  <p className="text-[10px] font-bold text-slate-800">Cash on Delivery</p>
                  <p className="text-[9px] text-slate-500">All Bangladesh</p>
                </div>
                <div className="p-2.5 rounded-xl bg-slate-50 border border-slate-100 space-y-1">
                  <ShieldCheck className="w-4 h-4 text-emerald-500 mx-auto" />
                  <p className="text-[10px] font-bold text-slate-800">100% Genuine</p>
                  <p className="text-[9px] text-slate-500">Quality Verified</p>
                </div>
                <div className="p-2.5 rounded-xl bg-slate-50 border border-slate-100 space-y-1">
                  <RotateCcw className="w-4 h-4 text-sky-500 mx-auto" />
                  <p className="text-[10px] font-bold text-slate-800">Fast Delivery</p>
                  <p className="text-[9px] text-slate-500">Steadfast Courier</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Bottom Section: Tabs for Description & Details and Reviews */}
        <section id="product-tabs-section" className="border-t border-slate-200 bg-slate-50/50 p-4 sm:p-6 lg:p-8">
          <div className="flex items-center gap-2 border-b border-slate-200 pb-3">
            <button
              type="button"
              onClick={() => setActiveTab('overview')}
              className={`px-4 py-2 rounded-xl text-xs sm:text-sm font-bold transition-all cursor-pointer ${
                activeTab === 'overview'
                  ? 'bg-slate-900 text-white shadow-xs'
                  : 'bg-white text-slate-600 hover:text-slate-900 border border-slate-200'
              }`}
            >
              Description & Details
            </button>

            <button
              type="button"
              onClick={() => setActiveTab('reviews')}
              className={`px-4 py-2 rounded-xl text-xs sm:text-sm font-bold transition-all cursor-pointer ${
                activeTab === 'reviews'
                  ? 'bg-slate-900 text-white shadow-xs'
                  : 'bg-white text-slate-600 hover:text-slate-900 border border-slate-200'
              }`}
            >
              Reviews ({totalReviewsCount})
            </button>
          </div>

          {/* Tab 1: Description & Details */}
          {activeTab === 'overview' && (
            <div className="pt-6 max-w-3xl space-y-6">
              <FormattedDescription content={product.description} />
            </div>
          )}

          {/* Tab 2: Reviews */}
          {activeTab === 'reviews' && (
            <div className="pt-6 space-y-8 animate-in fade-in duration-200">
              {/* SECTION A: REVIEW METRICS OVERVIEW & RATING BREAKDOWN */}
              <div className="bg-white rounded-3xl border border-slate-200/90 p-5 sm:p-7 shadow-xs">
                <div className="grid grid-cols-1 md:grid-cols-12 gap-6 lg:gap-8 items-center">
                  {/* Score & Stars Box */}
                  <div className="md:col-span-4 flex flex-col items-center justify-center p-4 sm:p-6 bg-amber-50/50 rounded-2xl border border-amber-100 text-center">
                    <span className="text-4xl sm:text-5xl font-black font-display text-slate-900 tracking-tight">
                      {reviewStats.averageRating.toFixed(1)}
                    </span>
                    <div className="flex items-center gap-1 my-2 text-amber-400">
                      {[1, 2, 3, 4, 5].map((starIdx) => (
                        <Star
                          key={starIdx}
                          className={`w-5 h-5 ${
                            starIdx <= Math.round(reviewStats.averageRating)
                              ? 'fill-amber-400 text-amber-400'
                              : 'text-slate-200'
                          }`}
                        />
                      ))}
                    </div>
                    <p className="text-xs font-bold text-slate-800">
                      Based on {reviewStats.totalReviews} {reviewStats.totalReviews === 1 ? 'review' : 'reviews'}
                    </p>
                    <div className="mt-3 inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-50 border border-emerald-200 text-emerald-800 text-[11px] font-bold">
                      <ShieldCheck className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                      <span>Verified Customers</span>
                    </div>
                  </div>

                  {/* Rating Breakdown Bar Chart */}
                  <div className="md:col-span-5 space-y-2">
                    <h4 className="text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                      Rating Breakdown
                    </h4>
                    {([5, 4, 3, 2, 1] as const).map((star) => {
                      const count = reviewStats.distribution[star] || 0;
                      const pct = reviewStats.distributionPercentages[star] || 0;
                      const isSelected = reviewStarFilter === star;

                      return (
                        <button
                          key={star}
                          type="button"
                          onClick={() => setReviewStarFilter(isSelected ? 'all' : star)}
                          className={`w-full flex items-center gap-2.5 text-xs py-1 px-2 rounded-xl transition-all cursor-pointer ${
                            isSelected
                              ? 'bg-amber-100/70 ring-1 ring-amber-300 font-bold'
                              : 'hover:bg-slate-50 text-slate-600'
                          }`}
                          title={`Filter by ${star} star reviews (${count})`}
                        >
                          <span className="w-12 text-left font-bold text-slate-700 flex items-center gap-1 shrink-0">
                            <span>{star} Star</span>
                          </span>

                          <div className="flex-1 h-2.5 bg-slate-100 rounded-full overflow-hidden border border-slate-200/60">
                            <div
                              className="h-full bg-amber-400 rounded-full transition-all duration-500 ease-out"
                              style={{ width: `${pct}%` }}
                            />
                          </div>

                          <span className="w-16 text-right font-mono text-[11px] text-slate-500 shrink-0">
                            {pct}% ({count})
                          </span>
                        </button>
                      );
                    })}
                  </div>

                  {/* Action / Call-to-Action */}
                  <div className="md:col-span-3 flex flex-col items-center sm:items-start justify-center gap-3 p-4 bg-slate-50 rounded-2xl border border-slate-200/70 text-center sm:text-left">
                    <div>
                      <h4 className="font-bold text-xs sm:text-sm text-slate-900">
                        Share Your Thoughts
                      </h4>
                      <p className="text-[11px] text-slate-500 mt-0.5">
                        Help other customers make verified purchasing choices.
                      </p>
                    </div>

                    <button
                      type="button"
                      id="open-write-review-btn"
                      onClick={() => setShowReviewForm((prev) => !prev)}
                      className="w-full py-2.5 px-4 rounded-xl bg-slate-900 hover:bg-black active:scale-95 text-white font-bold text-xs flex items-center justify-center gap-2 shadow-xs transition-all cursor-pointer"
                    >
                      <MessageSquare className="w-4 h-4 text-amber-400" />
                      <span>{showReviewForm ? 'Close Review Form' : 'Write a Review'}</span>
                    </button>
                  </div>
                </div>
              </div>

              {/* SECTION B: COLLAPSIBLE OR INLINE CUSTOMER REVIEW FORM */}
              {showReviewForm && (
                <div id="customer-review-form-card" className="bg-white rounded-3xl border-2 border-rose-500/20 shadow-md p-5 sm:p-7 space-y-5 animate-in fade-in duration-200">
                  <div className="flex items-center justify-between pb-3 border-b border-slate-100">
                    <div className="flex items-center gap-2.5">
                      <div className="w-9 h-9 rounded-xl bg-rose-50 text-rose-600 flex items-center justify-center">
                        <Sparkles className="w-5 h-5" />
                      </div>
                      <div>
                        <h3 className="font-display font-bold text-base text-slate-900">
                          Write a Customer Review
                        </h3>
                        <p className="text-xs text-slate-500">
                          Reviewing: <span className="font-semibold text-slate-800">{product.title}</span>
                        </p>
                      </div>
                    </div>
                    <button
                      type="button"
                      onClick={() => setShowReviewForm(false)}
                      className="p-1.5 rounded-full hover:bg-slate-100 text-slate-400 hover:text-slate-600 transition-colors cursor-pointer"
                    >
                      <X className="w-5 h-5" />
                    </button>
                  </div>

                  {reviewSuccessMsg && (
                    <div className="p-3.5 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-semibold flex items-center gap-2.5">
                      <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0" />
                      <span>{reviewSuccessMsg}</span>
                    </div>
                  )}

                  {reviewError && (
                    <div className="p-3.5 rounded-2xl bg-rose-50 border border-rose-200 text-rose-800 text-xs font-semibold flex items-center gap-2.5">
                      <AlertTriangle className="w-5 h-5 text-rose-600 shrink-0" />
                      <span>{reviewError}</span>
                    </div>
                  )}

                  <form onSubmit={handleReviewSubmit} className="space-y-4">
                    {/* Star Rating Picker */}
                    <div>
                      <label className="block text-xs font-bold text-slate-800 mb-1.5">
                        Your Rating <span className="text-rose-500">*</span>
                      </label>
                      <div className="flex items-center gap-2">
                        <div className="flex items-center gap-1 bg-slate-50 p-1.5 rounded-xl border border-slate-200">
                          {[1, 2, 3, 4, 5].map((star) => {
                            const effectiveRating = hoverRating !== null ? hoverRating : reviewRating;
                            return (
                              <button
                                key={star}
                                type="button"
                                onMouseEnter={() => setHoverRating(star)}
                                onMouseLeave={() => setHoverRating(null)}
                                onClick={() => setReviewRating(star)}
                                className="p-1.5 text-amber-400 hover:scale-115 transition-transform cursor-pointer"
                                title={`${star} Star${star > 1 ? 's' : ''}`}
                              >
                                <Star
                                  className={`w-6 h-6 transition-colors ${
                                    star <= effectiveRating
                                      ? 'fill-amber-400 text-amber-400 drop-shadow-xs'
                                      : 'text-slate-200'
                                  }`}
                                />
                              </button>
                            );
                          })}
                        </div>
                        <span className="text-xs font-bold text-slate-700 ml-1">
                          {hoverRating || reviewRating} / 5 —{' '}
                          {(hoverRating || reviewRating) === 5
                            ? 'Excellent! Highly satisfied'
                            : (hoverRating || reviewRating) === 4
                            ? 'Good, happy with purchase'
                            : (hoverRating || reviewRating) === 3
                            ? 'Average / Neutral'
                            : (hoverRating || reviewRating) === 2
                            ? 'Fair, had some issues'
                            : 'Poor, dissatisfied'}
                        </span>
                      </div>
                    </div>

                    {/* Author Name */}
                    <div>
                      <label className="block text-xs font-bold text-slate-800 mb-1">
                        Your Full Name <span className="text-rose-500">*</span>
                      </label>
                      <input
                        type="text"
                        value={reviewAuthor}
                        onChange={(e) => setReviewAuthor(e.target.value)}
                        placeholder="e.g. Farhan Chowdhury"
                        required
                        minLength={2}
                        maxLength={60}
                        className="w-full px-3.5 py-2.5 text-xs rounded-xl border border-slate-300 focus:border-rose-500 focus:ring-2 focus:ring-rose-500/20 focus:outline-none"
                      />
                    </div>

                    {/* Comment */}
                    <div>
                      <div className="flex items-center justify-between mb-1">
                        <label className="text-xs font-bold text-slate-800">
                          Your Review Comment <span className="text-rose-500">*</span>
                        </label>
                        <span className="text-[10px] text-slate-400 font-mono">
                          {reviewComment.length} / 1000 characters
                        </span>
                      </div>
                      <textarea
                        value={reviewComment}
                        onChange={(e) => setReviewComment(e.target.value)}
                        rows={4}
                        required
                        minLength={3}
                        maxLength={1000}
                        placeholder="Share details about the quality, build, delivery speed, and performance of this item..."
                        className="w-full px-3.5 py-2.5 text-xs rounded-xl border border-slate-300 focus:border-rose-500 focus:ring-2 focus:ring-rose-500/20 focus:outline-none leading-relaxed"
                      />
                    </div>

                    {/* Photo Attachments */}
                    <div>
                      <label className="block text-xs font-bold text-slate-800 mb-1 flex items-center justify-between">
                        <span className="flex items-center gap-1.5">
                          <Camera className="w-3.5 h-3.5 text-slate-500" />
                          <span>Attach Customer Photos (Optional, max 5)</span>
                        </span>
                        <span className="text-[10px] text-slate-400">{reviewImages.length}/5 uploaded</span>
                      </label>

                      {/* Photo Previews */}
                      {reviewImages.length > 0 && (
                        <div className="flex items-center gap-2 mb-2 flex-wrap">
                          {reviewImages.map((img, idx) => (
                            <div
                              key={idx}
                              className="relative w-16 h-16 rounded-xl overflow-hidden border border-slate-200 group"
                            >
                              <img src={img} alt={`Review photo ${idx + 1}`} className="w-full h-full object-cover" />
                              <button
                                type="button"
                                onClick={() => handleRemovePhoto(idx)}
                                className="absolute top-1 right-1 p-0.5 rounded-full bg-black/70 hover:bg-black text-white transition-colors cursor-pointer"
                                title="Remove photo"
                              >
                                <X className="w-3 h-3" />
                              </button>
                            </div>
                          ))}
                        </div>
                      )}

                      {reviewImages.length < 5 && (
                        <div className="space-y-1.5">
                          <div className="flex flex-col sm:flex-row gap-2">
                            <label className="flex-1 py-2 px-3 border border-dashed border-slate-300 hover:border-slate-400 rounded-xl bg-slate-50/70 hover:bg-slate-50 flex items-center justify-center gap-2 text-xs text-slate-600 font-medium cursor-pointer transition-colors">
                              <UploadCloud className="w-4 h-4 text-slate-500" />
                              <span>Upload Images from Device</span>
                              <input
                                type="file"
                                accept="image/jpeg,image/png,image/webp,image/gif,image/x-icon"
                                multiple
                                onChange={handlePhotoUpload}
                                className="hidden"
                              />
                            </label>

                            <div className="flex gap-1.5 sm:w-1/2">
                              <input
                                type="url"
                                value={reviewImageUrlInput}
                                onChange={(e) => setReviewImageUrlInput(e.target.value)}
                                placeholder="Or paste photo URL..."
                                className="flex-1 px-3 py-2 text-xs rounded-xl border border-slate-300 focus:border-rose-500 focus:outline-none"
                              />
                              <button
                                type="button"
                                onClick={handleAddImageUrl}
                                disabled={!reviewImageUrlInput.trim()}
                                className="px-3 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-xs disabled:opacity-40 cursor-pointer"
                              >
                                Add
                              </button>
                            </div>
                          </div>
                          <p className="text-[10px] text-slate-400">
                            Supports JPG, PNG, WebP, GIF, ICO up to 2MB each (max 5 photos). SVG files prohibited.
                          </p>
                        </div>
                      )}
                    </div>

                    {/* Guest Verified Purchase Claim (Optional) */}
                    <div className="p-3.5 bg-slate-50 rounded-2xl border border-slate-200/80 space-y-2">
                      <div className="flex items-center gap-1.5 text-xs font-bold text-slate-800">
                        <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                        <span>Already purchased this product from Rongdhonu? (Optional)</span>
                      </div>
                      <p className="text-[11px] text-slate-500 leading-normal">
                        Provide your order number & contact number to automatically receive the <strong>✔ Verified Purchase</strong> badge on your review.
                      </p>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1">
                        <input
                          type="text"
                          value={reviewOrderNumber}
                          onChange={(e) => setReviewOrderNumber(e.target.value)}
                          placeholder="Order ID / Number (e.g. 1002)"
                          className="w-full px-3 py-2 bg-white text-xs rounded-xl border border-slate-300 focus:outline-none focus:border-slate-500"
                        />
                        <input
                          type="tel"
                          value={reviewPhone}
                          onChange={(e) => setReviewPhone(e.target.value)}
                          placeholder="Phone Number (e.g. 01712345678)"
                          className="w-full px-3 py-2 bg-white text-xs rounded-xl border border-slate-300 focus:outline-none focus:border-slate-500"
                        />
                      </div>
                    </div>

                    <div className="pt-2 flex items-center justify-between">
                      <span className="text-[10px] text-slate-400">
                        Reviews are verified to protect against spam & manipulation.
                      </span>

                      <button
                        type="submit"
                        id="submit-customer-review-btn"
                        disabled={isSubmittingReview}
                        className="py-2.5 px-6 rounded-xl bg-rose-600 hover:bg-rose-700 active:scale-95 text-white font-bold text-xs shadow-xs transition-all flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
                      >
                        {isSubmittingReview ? (
                          <>
                            <RotateCcw className="w-3.5 h-3.5 animate-spin" />
                            <span>Submitting...</span>
                          </>
                        ) : (
                          <>
                            <Send className="w-3.5 h-3.5" />
                            <span>Submit Review</span>
                          </>
                        )}
                      </button>
                    </div>
                  </form>
                </div>
              )}

              {/* SECTION C: REVIEWS FILTER & SORT CONTROLS TOOLBAR */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-2 border-b border-slate-200">
                {/* Filter Pills */}
                <div className="flex items-center gap-1.5 flex-wrap">
                  <button
                    type="button"
                    onClick={() => setReviewStarFilter('all')}
                    className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                      reviewStarFilter === 'all'
                        ? 'bg-slate-900 text-white shadow-xs'
                        : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'
                    }`}
                  >
                    All ({reviewStats.totalReviews})
                  </button>

                  {([5, 4, 3, 2, 1] as const).map((star) => {
                    const count = reviewStats.distribution[star];
                    if (count === 0 && reviewStarFilter !== star) return null;
                    return (
                      <button
                        key={star}
                        type="button"
                        onClick={() => setReviewStarFilter(reviewStarFilter === star ? 'all' : star)}
                        className={`px-2.5 py-1.5 rounded-xl text-xs font-bold transition-all cursor-pointer flex items-center gap-1 ${
                          reviewStarFilter === star
                            ? 'bg-amber-500 text-white shadow-xs'
                            : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'
                        }`}
                      >
                        <span>{star}</span>
                        <Star className={`w-3 h-3 ${reviewStarFilter === star ? 'fill-white text-white' : 'fill-amber-400 text-amber-400'}`} />
                        <span>({count})</span>
                      </button>
                    );
                  })}

                  {reviewsWithPhotosCount > 0 && (
                    <button
                      type="button"
                      onClick={() => setReviewSortBy(reviewSortBy === 'photos' ? 'newest' : 'photos')}
                      className={`px-2.5 py-1.5 rounded-xl text-xs font-bold transition-all cursor-pointer flex items-center gap-1 ${
                        reviewSortBy === 'photos'
                          ? 'bg-rose-600 text-white shadow-xs'
                          : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'
                      }`}
                    >
                      <Camera className="w-3 h-3" />
                      <span>With Photos ({reviewsWithPhotosCount})</span>
                    </button>
                  )}
                </div>

                {/* Sort Dropdown */}
                <div className="flex items-center gap-2 self-end sm:self-auto shrink-0">
                  <span className="text-xs text-slate-500 font-medium">Sort by:</span>
                  <select
                    value={reviewSortBy}
                    onChange={(e) => setReviewSortBy(e.target.value as any)}
                    className="px-3 py-1.5 bg-white border border-slate-200 rounded-xl text-xs font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-rose-500/20 cursor-pointer"
                  >
                    <option value="newest">Newest First</option>
                    <option value="oldest">Oldest First</option>
                    <option value="highest">Highest Rating</option>
                    <option value="lowest">Lowest Rating</option>
                    <option value="photos">Photos First</option>
                  </select>
                </div>
              </div>

              {/* SECTION D: REVIEWS LIST DISPLAY */}
              <div className="space-y-4">
                {reviewStarFilter !== 'all' && (
                  <div className="flex items-center justify-between p-2.5 rounded-xl bg-amber-50 border border-amber-200 text-amber-900 text-xs font-bold">
                    <span>
                      Filtering by {reviewStarFilter}-Star reviews ({filteredAndSortedReviews.length})
                    </span>
                    <button
                      type="button"
                      onClick={() => setReviewStarFilter('all')}
                      className="text-amber-800 underline hover:text-amber-950 cursor-pointer"
                    >
                      Clear Filter
                    </button>
                  </div>
                )}

                {filteredAndSortedReviews.length === 0 ? (
                  <div className="p-8 sm:p-12 rounded-3xl bg-white border border-slate-200 text-center space-y-3 shadow-2xs">
                    <div className="w-12 h-12 rounded-2xl bg-amber-50 text-amber-500 flex items-center justify-center mx-auto">
                      <Star className="w-6 h-6 fill-amber-400" />
                    </div>
                    <div className="space-y-1">
                      <h4 className="font-bold text-sm sm:text-base text-slate-800">
                        {reviewStarFilter !== 'all'
                          ? `No ${reviewStarFilter}-Star Reviews Found`
                          : 'No Customer Reviews Yet'}
                      </h4>
                      <p className="text-xs text-slate-500 max-w-sm mx-auto">
                        {reviewStarFilter !== 'all'
                          ? 'Try clearing the star filter to see other verified customer reviews.'
                          : `Be the very first customer to review "${product.title}" and share your experience!`}
                      </p>
                    </div>
                    <div>
                      {reviewStarFilter !== 'all' ? (
                        <button
                          type="button"
                          onClick={() => setReviewStarFilter('all')}
                          className="px-4 py-2 rounded-xl bg-slate-900 hover:bg-black text-white text-xs font-bold transition-all cursor-pointer"
                        >
                          Show All Reviews
                        </button>
                      ) : (
                        <button
                          type="button"
                          onClick={() => {
                            setShowReviewForm(true);
                            setTimeout(() => {
                              document.getElementById('customer-review-form-card')?.scrollIntoView({ behavior: 'smooth' });
                            }, 50);
                          }}
                          className="px-5 py-2.5 rounded-xl bg-rose-600 hover:bg-rose-700 text-white text-xs font-bold shadow-xs transition-all cursor-pointer inline-flex items-center gap-1.5"
                        >
                          <Sparkles className="w-3.5 h-3.5" />
                          <span>Write the First Review</span>
                        </button>
                      )}
                    </div>
                  </div>
                ) : (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {filteredAndSortedReviews.map((rev) => (
                      <div
                        key={rev.id}
                        className="p-5 rounded-2xl bg-white border border-slate-200/90 shadow-2xs space-y-3 flex flex-col justify-between hover:border-slate-300 transition-colors"
                      >
                        <div className="space-y-2.5">
                          {/* Card Top: Author, Verified Badge, Rating & Date */}
                          <div className="flex items-start justify-between gap-2">
                            <div className="flex items-center gap-2.5 min-w-0">
                              <div className="w-8 h-8 rounded-full bg-linear-to-br from-slate-100 to-slate-200 border border-slate-300/80 flex items-center justify-center text-slate-700 font-extrabold text-xs shrink-0 shadow-2xs">
                                {(rev.authorName || rev.author || 'U').charAt(0).toUpperCase()}
                              </div>
                              <div className="min-w-0">
                                <p className="text-xs font-bold text-slate-900 truncate">
                                  {rev.authorName || rev.author || 'Verified Shopper'}
                                </p>
                                {rev.verifiedPurchase && (
                                  <span className="inline-flex items-center gap-1 text-[10px] font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-200">
                                    <CheckCircle2 className="w-3 h-3 text-emerald-600 shrink-0" />
                                    <span>Verified Purchase</span>
                                  </span>
                                )}
                              </div>
                            </div>

                            {/* Stars */}
                            <div className="flex items-center text-amber-400 shrink-0">
                              {[1, 2, 3, 4, 5].map((s) => (
                                <Star
                                  key={s}
                                  className={`w-3.5 h-3.5 ${
                                    s <= rev.rating
                                      ? 'fill-amber-400 text-amber-400'
                                      : 'text-slate-200'
                                  }`}
                                />
                              ))}
                            </div>
                          </div>

                          {/* Comment Text */}
                          <p className="text-xs text-slate-700 leading-relaxed break-words whitespace-pre-line">
                            {rev.comment}
                          </p>

                          {/* Attached Photo Gallery */}
                          {rev.images && rev.images.length > 0 && (
                            <div className="pt-1 flex items-center gap-2 flex-wrap">
                              {rev.images.map((imgUrl, imgIdx) => (
                                <button
                                  key={imgIdx}
                                  type="button"
                                  onClick={() =>
                                    setPreviewReviewImage({
                                      url: imgUrl,
                                      author: rev.authorName || rev.author || 'Shopper',
                                      rating: rev.rating,
                                    })
                                  }
                                  className="relative w-16 h-16 rounded-xl overflow-hidden border border-slate-200 hover:scale-105 active:scale-95 transition-all cursor-zoom-in group shadow-2xs"
                                  title="Click to zoom customer photo"
                                >
                                  <img
                                    src={imgUrl}
                                    alt={`Review photo ${imgIdx + 1}`}
                                    className="w-full h-full object-cover group-hover:opacity-95"
                                  />
                                </button>
                              ))}
                            </div>
                          )}
                        </div>

                        {/* Card Bottom: Date & Admin Delete Action */}
                        <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-[11px] text-slate-400">
                          <span className="font-medium">
                            {rev.createdAt
                              ? new Date(rev.createdAt).toLocaleDateString('en-GB', {
                                  day: 'numeric',
                                  month: 'short',
                                  year: 'numeric',
                                })
                              : 'Recent'}
                          </span>

                          {canDeleteReview && (
                            <button
                              type="button"
                              onClick={() => {
                                setConfirmDialog({
                                  isOpen: true,
                                  title: 'Delete Customer Review?',
                                  message: `Are you sure you want to delete this review by "${rev.authorName || rev.author || 'Shopper'}"?`,
                                  variant: 'danger',
                                  confirmText: 'Delete Review',
                                  onConfirm: () => {
                                    deleteProductReview(rev.id);
                                    setConfirmDialog((p) => ({ ...p, isOpen: false }));
                                  },
                                });
                              }}
                              className="p-1 rounded-md text-slate-400 hover:text-rose-600 hover:bg-rose-50 transition-colors cursor-pointer"
                              title="Delete review (Admin action)"
                            >
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          )}
        </section>
      </div>

      {/* Related Products Section */}
      {relatedProducts.length > 0 && (
        <section className="space-y-4 pt-4">
          <div className="flex items-center justify-between pb-2 border-b border-slate-200/80">
            <div>
              <h2 className="font-display font-extrabold text-lg sm:text-xl text-slate-900">
                Related in {category?.name || 'Category'}
              </h2>
              <p className="text-xs text-slate-500">More matching products from this collection</p>
            </div>
            {category && (
              <a
                href={getCategoryUrl(category.slug || category.id)}
                onClick={(e) => {
                  if (e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;
                  e.preventDefault();
                  navigateToCategory(category.id);
                }}
                className="text-xs font-bold text-rose-600 hover:text-rose-700"
              >
                View All &rarr;
              </a>
            )}
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-5">
            {relatedProducts.map((rel) => (
              <ProductCard key={rel.id} product={rel} />
            ))}
          </div>
        </section>
      )}

      {/* Fullscreen Lightbox Modal */}
      {isFullscreenOpen && (
        <div
          onClick={() => setIsFullscreenOpen(false)}
          className="fixed inset-0 z-[100000] bg-black/95 flex items-center justify-center p-4 backdrop-blur-md"
        >
          <button
            type="button"
            onClick={() => setIsFullscreenOpen(false)}
            className="absolute top-4 right-4 z-50 p-2.5 rounded-full bg-white/20 hover:bg-white/40 text-white transition-colors"
          >
            <ChevronLeft className="w-6 h-6 rotate-45" />
          </button>

          <div
            onClick={(e) => e.stopPropagation()}
            className="relative max-w-5xl max-h-[90vh] flex items-center justify-center"
          >
            <img
              src={activeImage}
              alt={product.title}
              className="max-w-full max-h-[85vh] object-contain rounded-xl shadow-2xl"
            />

            {imageList.length > 1 && (
              <>
                <button
                  type="button"
                  onClick={() =>
                    setSelectedImageIdx((prev) => (prev > 0 ? prev - 1 : imageList.length - 1))
                  }
                  className="absolute left-2 sm:left-4 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-black/50 hover:bg-black/80 text-white flex items-center justify-center"
                >
                  <ChevronLeft className="w-6 h-6" />
                </button>
                <button
                  type="button"
                  onClick={() =>
                    setSelectedImageIdx((prev) => (prev < imageList.length - 1 ? prev + 1 : 0))
                  }
                  className="absolute right-2 sm:right-4 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-black/50 hover:bg-black/80 text-white flex items-center justify-center"
                >
                  <ChevronRight className="w-6 h-6" />
                </button>
              </>
            )}
          </div>
        </div>
      )}

      {/* Confirm Dialog */}
      <ConfirmModal
        isOpen={confirmDialog.isOpen}
        title={confirmDialog.title}
        message={confirmDialog.message}
        confirmText={confirmDialog.confirmText}
        cancelText={confirmDialog.cancelText}
        variant={confirmDialog.variant}
        onConfirm={confirmDialog.onConfirm}
        onClose={() => setConfirmDialog((p) => ({ ...p, isOpen: false }))}
      />
    </div>
  );
};
